1
alvarezrrj/electro_experiencia pull request #2
Opened 2023-10-25 17:10 UTC by sunnyclat

subido materiales usados

2023-10-27 14:25 UTC, alvarezrrj commented
Estuve revisando el código y leyendo la docu de Prisma y me di cuenta de que esta tabla la genera sola Prisma cuando definimos una [relacion "many to many"](https://playground.prisma.io/guides/relations_many-to-many-implicit?step=0). Perdón por todo lo que has escrito!

Lo que necesitamos es hacer el modelo `Presupuesto` y ponerle una propiedad `materiales` de tipo `Material[]` y al modelo `Material` ponerle una propiedad `presupuestos` de tipo `Presupuesto[]`

2023-10-27 15:30 UTC, sunnyclat commented
Dale Rodri, yo voy a hacer otro push ahora ya que eso lo arregle, aunque tengo un problema con materiales y materiales usados en la parte de de findunique, pero bueno, ahi lo subo

2023-10-27 16:12 UTC, alvarezrrj commented
Nos organicemos

- Todo lo relacionado a materiales_usados (schema, controller, routes)  tiene que volar. A esa tabla la va a crear y administrar Prisma.
- Propongo que le pongamos el nombre en español, singular y con la primer letra en mayuscula a los modelos dentro de `schema.prisma` para que esté todo mas parejo.
- Tenés algún linter configurado? pregunto porque hay archivos en los que lo único que cambió es la indentación. Si es así compartimelo asi se mantiene prolijo el código.
- En adelante intentemos enviar cambios que sólo afecten una feature en cada PR para que sean mas amenas las revisiones.
- En las rutas de presupuestos y de materiales si vamos a necesitar los endpoints de crear, actualizar, y eliminar.

2023-10-27 16:23 UTC, alvarezrrj commented
Contame si queres que problema estás teniendo con `materiales` y lo vemos.

2023-10-27 19:17 UTC, sunnyclat commented
Ah entonces materiales_usados se borra.
 Dale le ponemos los nombres en español entonces a los modelos. 
Yo uso el formateo normal de typescript. 
Entonces en presupuestos y materiales le establezco un CRUD. Con respecto al problema que estoy teniendo, es en el archivo dentro de controllers en .ts de materiales en donde dice que type null is not assignable to type:

public static MaterialsRequestHandler: RequestParamHandler = async (
    req: MaterialsRequest,
    res,
    next,
    materials_id
  ) => {
    let mat: Materials | null;
    let validated = parseInt(materials_id);
    if (isNaN(validated)) {
      let err = new CustomError("materials_Id debe ser int");
      err.name = "400";
      return next(err);
    }

    try {
      mat = await prisma.materials.findUnique({
        where: {
          id: validated,
        },
        include: {

        
          Proveedor: {
            select: {
              id: true,
              name: true,
              telefono: true,
              email: true,
              detalles: true,

              createdAt: true,
              updatedAt: true,
            },
          },
          
        },
    
      });
    } catch (e) {
      return next(e);
    }
    if (!materials_id) {
      let err = new CustomError("Material no encontrado");
      err.name = "404";
      return next(err);
    }
    req.Materials = [mat];   

    next();
  };

2023-10-28 12:14 UTC, alvarezrrj commented
Me parece que el problema puede estar en esta línea `if (!materials_id) {`, acá deberías estar chequeando la existencia de `mat`, no `materials_id`. Acordate que según la interface `MaterialsRequest`, el valor de `req.Materials` deberia ser `Materials | undefined` y acá, en la línea `req.Materials = [mat]; ` le estás asignando un valor que es `Materials | null`.
Por eso deberías chequear `if(! mat)` para asegurarte de que `mat` no sea `null` antes de asignarselo a `req.Materials`

2023-10-28 16:09 UTC, sunnyclat commented
> Me parece que el problema puede estar en esta línea `if (!materials_id) {`, acá deberías estar chequeando la existencia de `mat`, no `materials_id`. Acordate que según la interface `MaterialsRequest`, el valor de `req.Materials` deberia ser `Materials | undefined` y acá, en la línea `req.Materials = [mat]; ` le estás asignando un valor que es `Materials | null`. Por eso deberías chequear `if(! mat)` para asegurarte de que `mat` no sea `null` antes de asignarselo a `req.Materials`

Gracias che!! era, eso jaj mira que estuve mirando y mirando no lo veia. Me faltan terminar los crud de las tablas y lo subo. Ya prepare presupuestos, materiales, proveedores, modificando en el schema en español y en singular

2023-11-06 15:41 UTC, alvarezrrj requested changes
Fijate en los comentarios. Apenas los hayas revisado mergeamos asi ya cerramos este PR.

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/prisma/schema.prisma
> +model Materials {
Estaría bueno renombrar `Materials` y `Proveedores` a `Material` y `Proveedor` para que todos los modelos estén en español y singular.

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/interfaces/interfaces.ts
> +import { usedMaterials } from "../controllers/usedMaterials";
Te aclaro acá para la próxima, lo que tenes que importar en esta línea es `Materiales_Usados` de "@prisma/client"

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/routes/material-routes.ts
> +router.delete('/materialId', Materiales.delete);
Falta una barra entre `material` y `Id`

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/routes/presupuesto-routes.ts
> +router.put('/presupuestoId', Presupuestos.update);
Falta una barra

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/routes/presupuesto-routes.ts
> +router.delete('/presupuestoId', Presupuestos.delete);
Acá también

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/prisma/schema.prisma
> +}
Acá hay que agregar `materiales Material[]` y `reparacionesNomencladas ReparacionNomenclada[]` para armar una relacion "many to many" https://playground.prisma.io/guides/relations_many-to-many-implicit?step=0

También `client_id` y `Usuario` tienen que ser `nullable`

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/controllers/presupuesto.ts
> +          },
El presupuesto debería incluir también todos los Materiales y Reparaciones Nomencladas.

Por otro lado, si vas a incluir todos los elementos del modelo relacionado, como en este caso que estas seleccionando todos los elementos de la `Recepcion`, podés poner `Recepcion: true`, en lugar de 
```javascript
          Recepcion: {
            select: {
              id: true,
              first_name: true,
              last_name: true,
              email: true,
              telefono: true,
              equipo: true,
              tipo: true,
              descripcion: true,
              createdAt: true,
              updatedAt: true,
              Employee:true,
            },
```
Así va a quedar mas limpia la cosa.

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/routes/proveedor-routes.ts
> +router.put('/proveedorId', Proveedores.update);
Falta una barra

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/routes/proveedor-routes.ts
> +router.delete('/proveedorId', Proveedores.delete);
Falta una barra

2023-11-06 15:41 UTC, alvarezrrj commented on usuario/src/controllers/proveedor.ts
> +          Materials: req.url.includes("materiales"),
Esta línea siempre va a dar `false` porque no definiste ninguna ruta que incluya "materiales"

2023-11-06 22:51 UTC, sunnyclat commented
Listo Rodri, ahi hice los cambios.

2023-11-08 12:50 UTC, alvarezrrj commented on usuario/prisma/schema.prisma
> +  Presupuesto   Presupuesto? @relation(fields: [presupuestoId], references: [id])
Este debería ser el último cambio: reemplazá esta línea por `presupuestos Presupuestos[]` y ahí cuando hagas la migración se debería generar una tabla que se llame _presupuestosToMateriales, o algo así. Lo mismo en el modelo `ReparacionNomenclada`
:point_down:

2023-11-08 13:05 UTC, alvarezrrj requested changes
Noté que en la migración no se habían creado las tablas pivote, las que generan la relación entre Presupuesto y Materiales y entre Presupuesto y Reparaciones Nomencladas. 

Te comenté las líneas que hay que modificar.

2023-11-08 13:05 UTC, alvarezrrj commented on usuario/prisma/schema.prisma
> +  Presupuesto   Presupuesto? @relation(fields: [presupuestoId], references: [id])
Lo mismo acá, cambiá esta línea por `presupuestos Presupuestos[]`

2023-11-09 00:38 UTC, sunnyclat commented
ahi hice los cambios Rodri. Se creo la tabla pivote y ahi lo pushee.

2023-11-10 13:37 UTC, alvarezrrj commented
Listo, lo junto a master :crossed_fingers:. Ahora para seguir hacé un `git switch master` y `git pull origin master` para traer los cambios a tu master local y después para hacer mas cambios hacete una rama nueva y empujá esa rama nueva. Se entiende?

2023-11-10 13:38 UTC, merged

2023-11-10 14:38 UTC, sunnyclat commented
Claro como el agua Rodri. Cambio a rama master para pullear y luego creo una rama nueva para seguir trabajando en ella.